.Dd March 15, 2025
.Dt WCJSON 3
.Os
.Sh NAME
.Nm wcjson ,
.Nm wctowcjsons ,
.Nm wctoascjsons ,
.Nm wcjsonstowc ,
.Nm WCJSON_INITIALIZER
.Nd wide character JSON
.Sh SYNOPSIS
.In wcjson.h
.Ft int
.Fn wcjson "struct wcjson *ctx" "const struct wcjson_ops *ops" "void *document" "const wchar_t *text" "const size_t len"
.Ft int
.Fn wctowcjsons "const wchar_t *s" "size_t s_len" "wchar_t *d" "size_t *d_lenp"
.Ft int
.Fn wctoascjsons "const wchar_t *s" "size_t s_len" "wchar_t *d" "size_t *d_lenp"
.Ft int
.Fn wcjsonstowc "const wchar_t *s" "size_t s_len" "wchar_t *d" "size_t *d_lenp"
.Sh DESCRIPTION
The
.Fn wcjson
function deserializes
.Fa len
characters JSON
.Fa text
by passing
.Fa ctx
and
.Fa document
to callback functions
.Fa ops .
.Pp
The
.Vt wcjson
structure is defined as follows:
.Bd -literal -offset indent
struct wcjson {
	enum wcjson_status status;
	int errnum;
};
.Ed
.Pp
The elements of this structure are defined as follows:
.Bl -tag -width errnum
.It Va status
Constant indicating status of an operation.
.Bl -tag -width WCJSON_ABORT_END_OF_INPUT -offset indent
.It Dv WCJSON_OK
An operation completed successfully.
.It Dv WCJSON_ABORT_ERROR
An operation aborted due to an error.
The
.Va errnum
member is describing the error.
.It Dv WCJSON_ABORT_INVALID
An operation aborted due to invalid JSON text.
.It Dv WCJSON_ABORT_END_OF_INPUT
An operation aborted due to an unexpected end of input.
.El
.It Va errnum
Code describing the error in case of
.Dv WCJSON_ABORT_ERROR .
.El
.Pp
The
.Dv WCJSON_INITIALIZER
macro expands to a rvalue expression initializing a
.Vt wcjson
structure.
.Pp
The
.Vt wcjson_ops
structure is defined as follows:
.Bd -literal -offset indent
struct wcjson_ops {
	void *(*object_start)(struct wcjson *ctx, void *doc,
	    void *parent);

	void (*object_add)(struct wcjson *ctx, void *doc,
	    void *obj, void *key,

	void (*object_end)(struct wcjson *ctx, void *doc,
	    void *obj);

	void *(*array_start)(struct wcjson *ctx, void *doc,
	    void *parent);

	void (*array_add)(struct wcjson *ctx, void *doc,
	    void *arr, void *value);

	void (*array_end)(struct wcjson *ctx, void *doc,
	    void *arr);

	void *(*string_value)(struct wcjson *ctx, void *doc,
	    const wchar_t *str, const size_t len,
	    const bool escaped);

	void *(*number_value)(struct wcjson *ctx, void *doc,
	    const wchar_t *num, const size_t len);

	void *(*bool_value)(struct wcjson *ctx, void *doc,
	    const bool value);

	void *(*null_value)(struct wcjson *ctx, void *doc);
};
.Ed
.Pp
The elements of this structure are defined as follows:
.Bl -tag -width array
.It Va object_start
Called whenever an opening '{' character of a JSON object has been scanned
to create a corresponding result node in
.Fa doc .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.It Va object_add
Called whenever a JSON object's key/value pair has been scanned to add
to
.Fa obj
with
.Fa key
and
.Fa value .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
.It Va object_end
Called whenever a closing '}' character of a JSON object has been scanned
to close
.Fa obj .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
.It Va array_start
Called whenever an opening '[' character of a JSON array has been scanned
to create a corresponding result node in
.Fa doc .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.It Va array_add
Called whenever a value of a JSON array has been scanned to add to
.Fa doc .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
.It Va array_end
Called whenever a closing ']' character of a JSON array has been scanned
to close
.Fa arr .
Except the
.Fa ctx
argument all arguments may be
.Dv NULL .
.It Va string_value
Called whenever a JSON string has been scanned to create a corresponding
result node in
.Fa doc
passing the string having been scanned in
.Fa str
of length
.Fa len .
The
.Fa escaped
flag indicates that string contains escape sequences.
The
.Fa doc
argument may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.It Va number_value
Called whenever a JSON number has been scanned to create a corresponding
result node in
.Fa doc
passing the number having been scanned in
.Fa num
of length
.Fa len .
The
.Fa doc
argument may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.It Va bool_value
Called whenever a JSON boolean has been scanned to create a corresponding
result node in
.Fa doc
passing the flag having been scanned in
.Fa value .
The
.Fa doc
argument may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.It Va null_value
Called whenever a JSON null value has been scanned to create a corresponding
result node in
.Fa doc .
The
.Fa doc
argument may be
.Dv NULL .
The function is expected to return a pointer to the result node or
.Dv NULL .
.El
.Pp
The (a)
.Fn wctowcjsons
and (b)
.Fn wctoascjsons
functions encode
.Fa s_len
characters from
.Fa s
to
.Fa d
capable of storing
.Fa *d_lenp
characters by applying JSON escaping rules (a) for all characters requiring
escaping according to the JSON grammar or additionally (b) for all characters
not compatible with 7bit ASCII.
To ensure the destination
.Fa d
is capable of storing the complete encoded representation of
.Fa s
the
.Dv WCJSON_ESCAPE_MAX
constant can be used such that *d_lenp >= s_len *
.Dv WCJSON_ESCAPE_MAX .
.Pp
The
.Fn wcjsonstowc
function decodes
.Fa s_len
characters from
.Fa s
to
.Fa d
capable of storing
.Fa *d_lenp
characters by unapplying JSON escaping rules.
To ensure the destination
.Fa d
is capable of storing the complete decoded representation of
.Fa s
that destination needs to be capable of storing at least
.Fa s_len
characters such that *d_lenp >= s_len.
.Pp
The
.Fn wctowcjsons ,
.Fn wctoascjsons
and
.Fn wcjsonstowc
functions set
.Fa *d_lenp
to the number of characters written to
.Fa d
on return.
.Sh RETURN VALUES
The functions return 0 on success or a negative value if a deserialization,
decoding or encoding error occurs.
The
.Fn wctowcjsons ,
.Fn wctoascjsons
and
.Fn wcjsonstowc
functions set the global variable
.Va errno
to indicate the error.
The
.Fn wcjson
function provides status via
.Fa ctx .
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er ERANGE
The size
.Fa *d_lenp
of a destination
.Fa d
was too small.
.It Bq Er EILSEQ
A source
.Fa s
cointained invalid data.
.El
.Sh STANDARDS
.Rs
.%A T. Bray, Ed.
.%D December 2017
.%R RFC 8259
.%T The JavaScript Object Notation (JSON) Data Interchange Format
.Re
.Pp
.Rs
.%A J. Klensin
.%D February 2008
.%R RFC 5137
.%T ASCII Escaping of Unicode Characters
.Re
.Pp
.Rs
.%A F. Yergeau
.%D November 2003
.%R RFC 3629
.%T UTF-8, a transformation format of ISO 10646
.Re
.Pp
.Rs
.%A P. Hoffman
.%A F. Yergeau
.%D February 2000
.%R RFC 2781
.%T UTF-16, an encoding of ISO 10646
.Re
.Sh AUTHORS
.An -nosplit
.An Christian Schulte Aq Mt cs@schulte.it .
